

spring:
  application:
    name: spi-application-tishko

# Configuration for the "development" profile
---
spring:
  config:
    additional-location: ./src/main/resources/application_local_dev.yaml
    activate:
      on-profile: development

development-property: dev-value

# Configuration for the "production" profile
---
spring:
  config:
    additional-location: ./src/main/resources/application_local_prod.yaml
    activate:
      on-profile: production

production-property: prod-value