test:
  value1: 19851985

spring:
  application:
    name: spi-application-tishko

  profiles:
    active: development

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: password123

  logging:
    level:
      org.springframework.web: DEBUG
  config:
    activate:
      on-profile: development
    additional-location: classpath:file:///d:/myPrj/spiEngine/src/main/resources/application_local.yaml

---

spring:
  datasource:
    url: jdbc:mysql://production-server:3306/mydatabase
    username: produser
    password: prodpassword

  logging:
    level:
      org.springframework.web: INFO
  config:
    activate:
      on-profile: production